In [1]:
import pandas as pd

In [2]:
colnames=['YEAR', 'TEAM', 'OFF', 'DEF','TEMPO','LUCK'] 
kp = pd.read_csv('kenpom.csv', names=colnames, header=None)
kp.head()

YEAR        TEAM    OFF   DEF  TEMPO   LUCK
0  2002        Duke  121.0  86.8   74.5 -0.027
1  2002  Cincinnati  118.1  87.9   67.4  0.002
2  2002    Maryland  119.2  89.9   73.7  0.025
3  2002      Kansas  118.7  89.7   77.3  0.022
4  2002    Oklahoma  114.9  88.9   66.5  0.043

In [3]:
for i in range(len(kp)):
    kp.loc[i,"TEAM"] = kp.loc[i,"TEAM"].lower()
kp.head()

YEAR        TEAM    OFF   DEF  TEMPO   LUCK
0  2002        duke  121.0  86.8   74.5 -0.027
1  2002  cincinnati  118.1  87.9   67.4  0.002
2  2002    maryland  119.2  89.9   73.7  0.025
3  2002      kansas  118.7  89.7   77.3  0.022
4  2002    oklahoma  114.9  88.9   66.5  0.043

In [4]:
punctuations = '.'

for i in range(len(kp)):
    team = kp.loc[i,"TEAM"]
    no_punct = ""
    for char in team:
       if char not in punctuations:
           no_punct = no_punct + char
    
    kp.loc[i,"TEAM"] = no_punct

In [5]:
kp.loc[kp['TEAM'] == "illinois"]

YEAR      TEAM    OFF    DEF  TEMPO   LUCK
7     2002  illinois  115.7   92.5   68.5  0.016
324   2003  illinois  113.2   88.7   67.8 -0.029
652   2004  illinois  117.8   95.7   63.5  0.055
961   2005  illinois  122.3   89.6   64.1 -0.007
1288  2006  illinois  114.5   91.3   62.1 -0.019
1635  2007  illinois  107.3   89.8   62.0 -0.017
1970  2008  illinois  107.5   94.0   61.0 -0.119
2264  2009  illinois  106.8   88.1   62.8  0.001
2616  2010  illinois  109.2   94.8   66.6 -0.029
2897  2011  illinois  113.3   93.1   64.8 -0.074
3275  2012  illinois  104.3   94.8   64.2 -0.005
3558  2013  illinois  110.6   94.8   64.6  0.042
3892  2014  illinois  106.5   93.4   61.2  0.007
4220  2015  illinois  108.3   96.7   64.8 -0.026
4604  2016  illinois  106.9  103.0   68.1  0.020
4865  2017  illinois  107.2   95.8   66.7  0.028
5221  2018  illinois  109.6  103.0   69.9 -0.093

In [6]:
colnames=['YEAR', 'SCORE_1','TEAM_1','TEAM_2','SCORE_2'] 
df = pd.read_csv('Big_Dance_CSV.csv', names=colnames, header=None)
df.head()

YEAR  SCORE_1      TEAM_1        TEAM_2  SCORE_2
0  1985       83    St Johns      Southern       59
1  1985       81         VCU      Marshall       65
2  1985       65    NC State        Nevada       56
3  1985       85        UNLV  San Diego St       80
4  1985       58  Washington      Kentucky       65

In [7]:
import numpy as np
df['OFF_1' ] = np.nan
df['DEF_1' ] = np.nan
df['TEMPO_1' ] = np.nan
df['LUCK_1' ] = np.nan
df['OFF_2' ] = np.nan
df['DEF_2' ] = np.nan
df['TEMPO_2' ] = np.nan
df['LUCK_2' ] = np.nan



In [8]:
df.head()

YEAR  SCORE_1      TEAM_1        TEAM_2  SCORE_2  OFF_1  DEF_1  TEMPO_1  \
0  1985       83    St Johns      Southern       59    NaN    NaN      NaN   
1  1985       81         VCU      Marshall       65    NaN    NaN      NaN   
2  1985       65    NC State        Nevada       56    NaN    NaN      NaN   
3  1985       85        UNLV  San Diego St       80    NaN    NaN      NaN   
4  1985       58  Washington      Kentucky       65    NaN    NaN      NaN   

   LUCK_1  OFF_2  DEF_2  TEMPO_2  LUCK_2  
0     NaN    NaN    NaN      NaN     NaN  
1     NaN    NaN    NaN      NaN     NaN  
2     NaN    NaN    NaN      NaN     NaN  
3     NaN    NaN    NaN      NaN     NaN  
4     NaN    NaN    NaN      NaN     NaN

In [9]:
for i in range(len(df)):
    df.loc[i,"TEAM_1"] = df.loc[i,"TEAM_1"].lower()

punctuations = '.'

for i in range(len(df)):
    team = df.loc[i,"TEAM_1"]
    no_punct = ""
    for char in team:
       if char not in punctuations:
           no_punct = no_punct + char
    
    df.loc[i,"TEAM_1"] = no_punct
df.head()

YEAR  SCORE_1      TEAM_1        TEAM_2  SCORE_2  OFF_1  DEF_1  TEMPO_1  \
0  1985       83    st johns      Southern       59    NaN    NaN      NaN   
1  1985       81         vcu      Marshall       65    NaN    NaN      NaN   
2  1985       65    nc state        Nevada       56    NaN    NaN      NaN   
3  1985       85        unlv  San Diego St       80    NaN    NaN      NaN   
4  1985       58  washington      Kentucky       65    NaN    NaN      NaN   

   LUCK_1  OFF_2  DEF_2  TEMPO_2  LUCK_2  
0     NaN    NaN    NaN      NaN     NaN  
1     NaN    NaN    NaN      NaN     NaN  
2     NaN    NaN    NaN      NaN     NaN  
3     NaN    NaN    NaN      NaN     NaN  
4     NaN    NaN    NaN      NaN     NaN

In [10]:
for i in range(len(df)):
    df.loc[i,"TEAM_2"] = df.loc[i,"TEAM_2"].lower()

punctuations = '.'

for i in range(len(df)):
    team = df.loc[i,"TEAM_2"]
    no_punct = ""
    for char in team:
       if char not in punctuations:
           no_punct = no_punct + char
    
    df.loc[i,"TEAM_2"] = no_punct
df.head()

YEAR  SCORE_1      TEAM_1        TEAM_2  SCORE_2  OFF_1  DEF_1  TEMPO_1  \
0  1985       83    st johns      southern       59    NaN    NaN      NaN   
1  1985       81         vcu      marshall       65    NaN    NaN      NaN   
2  1985       65    nc state        nevada       56    NaN    NaN      NaN   
3  1985       85        unlv  san diego st       80    NaN    NaN      NaN   
4  1985       58  washington      kentucky       65    NaN    NaN      NaN   

   LUCK_1  OFF_2  DEF_2  TEMPO_2  LUCK_2  
0     NaN    NaN    NaN      NaN     NaN  
1     NaN    NaN    NaN      NaN     NaN  
2     NaN    NaN    NaN      NaN     NaN  
3     NaN    NaN    NaN      NaN     NaN  
4     NaN    NaN    NaN      NaN     NaN

In [11]:
test = kp.loc[(kp['TEAM'] == "illinois") & (kp['YEAR'] == 2002)]
test.head()

YEAR      TEAM    OFF   DEF  TEMPO   LUCK
7  2002  illinois  115.7  92.5   68.5  0.016

In [12]:
for index, rows in test.iterrows(): 
    my_list =[rows.OFF, rows.DEF, rows.TEMPO,rows.LUCK]
print(my_list)

[115.7, 92.5, 68.5, 0.016]


In [13]:
for i in range(len(df)):
    team = df.loc[i,"TEAM_1"]
    year = df.loc[i,"YEAR"]
    try:
        test = kp.loc[(kp['TEAM'] == team ) & (kp['YEAR'] == year)]
        for index, rows in test.iterrows(): 
            my_list =[rows.OFF, rows.DEF, rows.TEMPO,rows.LUCK]
        df.loc[i,"OFF_1"] = my_list[0]
        df.loc[i,"DEF_1"] = my_list[1]
        df.loc[i,"TEMPO_1"] = my_list[2]
        df.loc[i,"LUCK_1"] = my_list[3]
    except:
        continue
df.head()
        

YEAR  SCORE_1      TEAM_1        TEAM_2  SCORE_2  OFF_1  DEF_1  TEMPO_1  \
0  1985       83    st johns      southern       59  115.7   92.5     68.5   
1  1985       81         vcu      marshall       65  115.7   92.5     68.5   
2  1985       65    nc state        nevada       56  115.7   92.5     68.5   
3  1985       85        unlv  san diego st       80  115.7   92.5     68.5   
4  1985       58  washington      kentucky       65  115.7   92.5     68.5   

   LUCK_1  OFF_2  DEF_2  TEMPO_2  LUCK_2  
0   0.016    NaN    NaN      NaN     NaN  
1   0.016    NaN    NaN      NaN     NaN  
2   0.016    NaN    NaN      NaN     NaN  
3   0.016    NaN    NaN      NaN     NaN  
4   0.016    NaN    NaN      NaN     NaN

In [14]:
for i in range(len(df)):
    team = df.loc[i,"TEAM_2"]
    year = df.loc[i,"YEAR"]
    try:
        test = kp.loc[(kp['TEAM'] == team ) & (kp['YEAR'] == year)]
        for index, rows in test.iterrows(): 
            my_list =[rows.OFF, rows.DEF, rows.TEMPO,rows.LUCK]
        df.loc[i,"OFF_2"] = my_list[0]
        df.loc[i,"DEF_2"] = my_list[1]
        df.loc[i,"TEMPO_2"] = my_list[2]
        df.loc[i,"LUCK_2"] = my_list[3]
    except:
        continue
df.head()

YEAR  SCORE_1      TEAM_1        TEAM_2  SCORE_2  OFF_1  DEF_1  TEMPO_1  \
0  1985       83    st johns      southern       59  115.7   92.5     68.5   
1  1985       81         vcu      marshall       65  115.7   92.5     68.5   
2  1985       65    nc state        nevada       56  115.7   92.5     68.5   
3  1985       85        unlv  san diego st       80  115.7   92.5     68.5   
4  1985       58  washington      kentucky       65  115.7   92.5     68.5   

   LUCK_1  OFF_2  DEF_2  TEMPO_2  LUCK_2  
0   0.016  114.7   90.5     64.9   0.052  
1   0.016  114.7   90.5     64.9   0.052  
2   0.016  114.7   90.5     64.9   0.052  
3   0.016  114.7   90.5     64.9   0.052  
4   0.016  114.7   90.5     64.9   0.052

In [15]:
df = df[df.YEAR > 2001]

In [17]:
df.head()

YEAR  SCORE_1      TEAM_1                  TEAM_2  SCORE_2  OFF_1  \
1071  2002       84        duke                winthrop       37  121.0   
1072  2002       86     alabama        florida atlantic       78  114.0   
1073  2002       71  pittsburgh  central connecticut st       54  112.1   
1074  2002       89         usc          unc wilmington       93  112.8   
1075  2002       75     indiana                    utah       56  114.0   

      DEF_1  TEMPO_1  LUCK_1  OFF_2  DEF_2  TEMPO_2  LUCK_2  
1071   86.8     74.5  -0.027   97.3  102.6     65.9   0.038  
1072   95.3     68.0   0.076   99.6  102.1     70.2   0.060  
1073   92.2     63.8   0.000   99.6  102.1     70.2   0.060  
1074   92.1     70.1  -0.051  107.4   96.1     63.9  -0.003  
1075   89.2     65.6  -0.049  111.4   97.3     62.1   0.010

In [17]:
import pickle
df.to_pickle("ncaa_ml.pkl")
#df = pd.read_pickle("ncaa_ml.pkl")

In [18]:
f2d = ['YEAR','SCORE_1','TEAM_1','TEAM_2','SCORE_2']
x = df[['OFF_1','DEF_1','TEMPO_1','LUCK_1','OFF_2','DEF_2','TEMPO_2','LUCK_2']].values
y = df[['SCORE_1','SCORE_2']].values

In [19]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.metrics import confusion_matrix, accuracy_score


In [20]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
model_lin = LinearRegression()  
model_lin.fit(X_train, y_train) #training the algorithm

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [54]:
test = df.loc[df['DEF_1'] == None]
test.head()

Empty DataFrame
Columns: [YEAR, SCORE_1, TEAM_1, TEAM_2, SCORE_2, OFF_1, DEF_1, TEMPO_1, LUCK_1, OFF_2, DEF_2, TEMPO_2, LUCK_2]
Index: []

In [16]:
df = df[df.YEAR < 2019]

In [58]:
df.tail()

YEAR  SCORE_1          TEAM_1      TEAM_2  SCORE_2  OFF_1  DEF_1  \
2137  2018       71       villanova  texas tech       59  127.8   94.0   
2138  2018       85          kansas        duke       81  120.9   97.4   
2139  2018       57  loyola chicago    michigan       69  111.4   95.0   
2140  2018       95       villanova      kansas       79  127.8   94.0   
2141  2018       62        michigan   villanova       79  114.7   90.5   

      TEMPO_1  LUCK_1  OFF_2  DEF_2  TEMPO_2  LUCK_2  
2137     68.7  -0.018  113.3   90.8     66.7  -0.007  
2138     68.8   0.076  122.4   93.6     69.7  -0.034  
2139     65.5   0.077  114.7   90.5     64.9   0.052  
2140     68.7  -0.018  120.9   97.4     68.8   0.076  
2141     64.9   0.052  127.8   94.0     68.7  -0.018

In [21]:
y_pred = model_lin.predict(X_test)
y_pred

array([[ 76.01988689,  72.55286757],
       [ 62.81149686,  60.17068622],
       [ 68.48561867,  68.68941927],
       [ 67.79720562,  70.10638789],
       [ 87.34702004,  78.2633736 ],
       [ 62.63411972,  61.95780674],
       [ 66.63227063,  61.279228  ],
       [ 69.73095458,  76.14285847],
       [ 64.41245081,  66.55925087],
       [ 75.77501154,  65.89961974],
       [ 82.99591437,  75.1440531 ],
       [ 76.21442276,  73.22897473],
       [ 67.27177663,  75.34017084],
       [ 79.01380032,  68.80519435],
       [ 74.55746339,  72.00089237],
       [ 68.29252945,  65.34141405],
       [ 78.59599338,  81.79198993],
       [ 71.96784857,  64.77796549],
       [ 62.02473138,  59.95271881],
       [ 64.34510876,  71.11258805],
       [ 69.53858496,  69.51415288],
       [ 90.85282416,  59.62049958],
       [ 65.65523533,  67.39183893],
       [ 67.67526621,  74.72094174],
       [ 69.20555213,  59.77955137],
       [ 76.30407324,  67.35039096],
       [ 73.63681466,  68.16370189],
 

In [22]:
prediction = pd.DataFrame({'Actual': y_test.flatten(), 'Predicted': y_pred.flatten().round()})
prediction


Actual  Predicted
0        78       76.0
1        61       73.0
2        55       63.0
3        59       60.0
4        71       68.0
5        86       69.0
6        70       68.0
7        77       70.0
8        95       87.0
9        79       78.0
10       56       63.0
11       62       62.0
12       53       67.0
13       55       61.0
14       54       70.0
15       58       76.0
16       75       64.0
17       71       67.0
18       76       76.0
19       71       66.0
20       81       83.0
21       73       75.0
22       84       76.0
23       68       73.0
24       73       67.0
25       77       75.0
26       93       79.0
27       64       69.0
28       64       75.0
29       74       72.0
..      ...        ...
400      90       81.0
401      52       54.0
402      72       80.0
403      53       57.0
404      83       87.0
405      67       65.0
406      86       84.0
407      60       74.0
408      79       73.0
409      68       66.0
410      74       86.0
411      48       67.0
412      74       77.0
413      77       82.0
414      74       77.0
415      62       67.0
416      80       75.0
417      64       66.0
418      76       78.0
419      50       62.0
420      85       76.0
421      67       68.0
422      64       68.0
423      55       63.0
424      84       60.0
425      83       58.0
426      89       72.0
427      70       59.0
428      73       85.0
429      69       79.0

[430 rows x 2 columns]

In [29]:
y_pred = y_pred.round()
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 8.22558139535
Mean Squared Error: 107.644186047
Root Mean Squared Error: 10.3751716153


In [26]:
final = [[111.1,99.6,62.3,.009,117.7,97.6,67.8,-.038]]
final = np.asarray(final)
final_score = model_lin.predict(final)
final_score

array([[ 66.66570794,  75.93155444]])

In [31]:
from sklearn.ensemble import RandomForestRegressor
model_rf = RandomForestRegressor()
model_rf.fit(X_train, y_train)
y_pred = model_rf.predict(X_test)
y_pred = y_pred.round()
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 8.8023255814
Mean Squared Error: 124.672093023
Root Mean Squared Error: 11.1656658119


In [32]:
from sklearn.linear_model import ARDRegression

In [23]:
y_test

array([[ 78,  61],
       [ 55,  59],
       [ 71,  86],
       [ 70,  77],
       [ 95,  79],
       [ 56,  62],
       [ 53,  55],
       [ 54,  58],
       [ 75,  71],
       [ 76,  71],
       [ 81,  73],
       [ 84,  68],
       [ 73,  77],
       [ 93,  64],
       [ 64,  74],
       [ 64,  68],
       [ 79,  93],
       [ 72,  64],
       [ 60,  49],
       [ 78,  76],
       [ 67,  58],
       [112,  69],
       [ 70,  60],
       [102,  87],
       [ 78,  60],
       [ 76,  59],
       [ 69,  56],
       [ 76,  73],
       [ 73,  71],
       [ 81,  88],
       [ 76,  63],
       [ 64,  63],
       [ 64,  75],
       [ 74,  69],
       [ 78,  71],
       [ 68,  53],
       [ 57,  50],
       [ 74,  69],
       [ 84,  81],
       [ 71,  53],
       [ 62,  78],
       [ 85,  65],
       [ 65,  60],
       [ 68,  87],
       [ 64,  67],
       [ 60,  79],
       [ 72,  64],
       [ 59,  44],
       [ 88,  59],
       [ 47,  63],
       [ 62,  68],
       [ 78,  86],
       [ 74,

In [25]:
y_pred

array([[ 76.01988689,  72.55286757],
       [ 62.81149686,  60.17068622],
       [ 68.48561867,  68.68941927],
       [ 67.79720562,  70.10638789],
       [ 87.34702004,  78.2633736 ],
       [ 62.63411972,  61.95780674],
       [ 66.63227063,  61.279228  ],
       [ 69.73095458,  76.14285847],
       [ 64.41245081,  66.55925087],
       [ 75.77501154,  65.89961974],
       [ 82.99591437,  75.1440531 ],
       [ 76.21442276,  73.22897473],
       [ 67.27177663,  75.34017084],
       [ 79.01380032,  68.80519435],
       [ 74.55746339,  72.00089237],
       [ 68.29252945,  65.34141405],
       [ 78.59599338,  81.79198993],
       [ 71.96784857,  64.77796549],
       [ 62.02473138,  59.95271881],
       [ 64.34510876,  71.11258805],
       [ 69.53858496,  69.51415288],
       [ 90.85282416,  59.62049958],
       [ 65.65523533,  67.39183893],
       [ 67.67526621,  74.72094174],
       [ 69.20555213,  59.77955137],
       [ 76.30407324,  67.35039096],
       [ 73.63681466,  68.16370189],
 

In [26]:
y_pred.size()

TypeError: 'int' object is not callable

In [27]:
y_pred.shape[0]

215

In [29]:
y_pred[0][0]

76.019886886335968

In [30]:
sum = 0
for row in y_pred:
    for num in row:
        sum = sum + num
        
print(sum/430)

69.5334598516


In [31]:
8.8023255814/69.5334598516

0.1265912209774422